# Generated by Django 2.2.5 on 2020-04-28 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('CE', '1'), ('CSE', '2'), ('ME', '3'), ('ECE', '4'), ('EI', '5'), ('EE', '6')], default='CE', max_length=6)),
                ('schId', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[('Medical', '1'), ('Inter-NIT', '2'), ('Others', '3')], default='Medical', max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='HODRegister',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('CE', '1'), ('CSE', '2'), ('ME', '3'), ('ECE', '4'), ('EI', '5'), ('EE', '6')], default='CE', max_length=6)),
                ('tid', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('CE', '1'), ('CSE', '2'), ('ME', '3'), ('ECE', '4'), ('EI', '5'), ('EE', '6')], default='CE', max_length=6)),
                ('schId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
            ],
        ),
    ]
