# Generated by Django 2.2.5 on 2020-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp','__first__'),
        ('basicapp', '0003_auto_20200429_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='schId',
            field=models.SmallIntegerField(default='', editable=False, unique=True),
        ),
    ]
