# Generated by Django 2.2.5 on 2020-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20200429_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='schId',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
