# Generated by Django 2.2.5 on 2020-07-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20200711_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='explain',
            field=models.TextField(default=None),
        ),
    ]
