# Generated by Django 2.2.5 on 2020-07-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_application_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='explain',
            field=models.TextField(null=True),
        ),
    ]
