# Generated by Django 2.2.5 on 2020-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_application_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Inter-NIT', 'Medical'), ('Others', 'Medical')], default='Medical', max_length=20),
        ),
    ]
