# Generated by Django 2.2.5 on 2020-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0011_auto_20200715_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Inter-NIT', 'Inter-NIT'), ('Others', 'Others')], default='Medical', max_length=20),
        ),
    ]
